// Hand-written bridge between the emscripten kernel module and the Dart web
// binding (lib/ffi/sketch_kernel_web.dart). All wasm-heap pointer marshalling
// lives here so the Dart side stays a plain method-call surface.
//
// sketch_kernel.js (the emscripten MODULARIZE factory `createSketchKernel`) is
// generated by build_wasm.sh and loaded before this script.
var SketchKernelJS = null;

var SketchKernelReady = createSketchKernel().then(function (M) {
  function allocDoubles(arr) {
    var p = M._malloc(arr.length * 8);
    for (var i = 0; i < arr.length; i++) M.setValue(p + i * 8, arr[i], 'double');
    return p;
  }
  var I = ['number'], II = ['number', 'number'];
  function call(name, ret, types, args) { return M.ccall(name, ret, types, args); }

  SketchKernelJS = {
    version: function () { return call('sk_version', 'number', [], []); },

    fitLine: function (flat, n) {
      var inp = allocDoubles(flat), out = M._malloc(32);
      var ok = call('sk_fit_line', 'number', ['number', 'number', 'number'], [inp, n, out]);
      var r = ok ? [M.getValue(out, 'double'), M.getValue(out + 8, 'double'),
                    M.getValue(out + 16, 'double'), M.getValue(out + 24, 'double')] : null;
      M._free(inp); M._free(out);
      return r;
    },
    fitCircle: function (flat, n) {
      var inp = allocDoubles(flat), out = M._malloc(32);
      var ok = call('sk_fit_circle', 'number', ['number', 'number', 'number'], [inp, n, out]);
      var r = ok ? [M.getValue(out, 'double'), M.getValue(out + 8, 'double'),
                    M.getValue(out + 16, 'double'), M.getValue(out + 24, 'double')] : null;
      M._free(inp); M._free(out);
      return r;
    },

    create: function () { return call('sk_create', 'number', [], []); },
    destroy: function (h) { call('sk_destroy', null, I, [h]); },
    addPoint: function (h, x, y) { return call('sk_add_point', 'number', ['number', 'number', 'number'], [h, x, y]); },
    fixPoint: function (h, id, fixed) { call('sk_fix_point', null, ['number', 'number', 'number'], [h, id, fixed]); },
    addConstraint: function (h, t, a, b, c, d, v) {
      return call('sk_add_constraint', 'number',
        ['number', 'number', 'number', 'number', 'number', 'number', 'number'], [h, t, a, b, c, d, v]);
    },
    solve: function (h) { return call('sk_solve', 'number', I, [h]); },
    point: function (h, id) {
      var buf = M._malloc(16);
      call('sk_point', null, ['number', 'number', 'number', 'number'], [h, id, buf, buf + 8]);
      var r = [M.getValue(buf, 'double'), M.getValue(buf + 8, 'double')];
      M._free(buf);
      return r;
    },
    addRadius: function (h, v) { return call('sk_add_radius', 'number', II, [h, v]); },
    radius: function (h, id) { return call('sk_radius', 'number', II, [h, id]); },
    conRadius: function (h, id, v) { return call('sk_constrain_radius', 'number', ['number', 'number', 'number'], [h, id, v]); },
    conPoc: function (h, pt, center, rad) { return call('sk_constrain_point_on_circle', 'number', ['number', 'number', 'number', 'number'], [h, pt, center, rad]); },
    conTan: function (h, p1, p2, center, rad) { return call('sk_constrain_tangent_line', 'number', ['number', 'number', 'number', 'number', 'number'], [h, p1, p2, center, rad]); },
  };
  return SketchKernelJS;
});
